### ISSUE TITLE
Dialyzer errors

### ISSUE THREAD

**Issue by maehr** [riverrun/argon2_elixir#13]
`mix dialyzer` returns the following errors with using Comeonin v4.0.3 with Argon2 v1.2.11 on OSX 10.13 (Bcrypt works just fine). It does not matter whether I use checkpw(password, hash) or check_pass(user, password, opts \\ []) to verify the login credentials.
...: Guard test 'or'('false','false') can never succeed
...: Function authentication_failed/0 will never be called
...: The pattern {'ok', _} can never match the type {'error',<<_:64,_:_*8>>}

PS: Compiler seems to be working.

cc -std=c89 -pthread -O3 -Wall -g -Iargon2/include -Iargon2/src -Ic_src -I/usr/local/Cellar/erlang/20.1.4/lib/erlang/erts-9.1.3/include -march=native -dynamiclib -undefined dynamic_lookup  argon2/src/argon2.c argon2/src/core.c argon2/src/blake2/blake2b.c argon2/src/thread.c argon2/src/encoding.c c_src/argon2_nif.c argon2/src/opt.c -o priv/argon2_nif.so

**Comment by riverrun** [comment]
We have had [this issue](https://github.com/riverrun/comeonin/issues/118) before. It definitely seems like a false report.

If you could report it to dialyzer, then they might be able to help us solve this issue.

**Comment by riverrun** [comment]
Any news?

**Comment by riverrun** [comment]
Closing. If you have any further news, please feel free to reopen this issue.

**Comment by danielbarbarito** [comment]
This is really annoying. Does anybody have any solution to this?

**Comment by riverrun** [comment]
There's an [issue](https://github.com/elixir-lang/elixir/issues/7351) open about the dialyzer warnings with `with`.

**Comment by riverrun** [comment]
I have updated Comeonin to version 4.1.1. That contains a possible fix. If you could test it and see if it works, that would be very helpful.

**Comment by danielbarbarito** [comment]
@riverrun Worked for me! Thanks so much. Love the library by the way!

**Comment by riverrun** [comment]
I just changed the `with` clause to a `case`. I'm glad to hear it worked for at least one person :)

**Comment by BlueHotDog** [comment]
still having the same issue.. even though it seems like it's an issue with dialyzer, i think it's worth the time to at least address it here in one way or another.. anyone have any idea how to quick-fix this?

**Comment by NobbZ** [comment]
This is **not** a bug in dialyzer.

I did some research about how dialyzer works with NIFs. Guess what, it does not, at all…

It only sees the stub-functions placed in the module.

So dialyzer thinks, that a call to any of `Argon2.Base.*_nif/*` will always result in an `exit/1`. This causes the dialyzer complains regarding this project.

Instead of doing an arbitrary exit in NIF-stubs one should either implement a erlang/elixir-version of the algorithm as fall back or call [`:erlang.nif_error/1/2`](http://erlang.org/doc/man/erlang.html#nif_error-1) to make dialyzer happy.
